export default [
  {
    "_id": "A101",
    "title": "Propulsion Assignment",
    "course": "RS101",
    "points": 100,
    "group": "ASSIGNMENTS",
    "gradeDisplay": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-13",
    "availableFrom": "2024-05-06",
    "availableUntil": "2024-05-20",
    "description": "Submit a Netlify link to your propulsion assignment."
  },
  {
    "_id": "A102",
    "title": "Combustion Analysis",
    "course": "RS101",
    "points": 100,
    "group": "QUIZZES",
    "gradeDisplay": "Points",
    "submissionType": "Online",
    "onlineEntryOptions": ["Text Entry", "Media Recordings"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-20",
    "availableFrom": "2024-05-13",
    "availableUntil": "2024-05-27",
    "description": "Analyze combustion efficiency and submit your report."
  },
  {
    "_id": "A103",
    "title": "Nozzle Design Project",
    "course": "RS101",
    "points": 150,
    "group": "PROJECTS",
    "gradeDisplay": "Complete/Incomplete",
    "submissionType": "External Tool",
    "onlineEntryOptions": [],
    "assignTo": "Team Alpha",
    "dueDate": "2024-05-30",
    "availableFrom": "2024-05-15",
    "availableUntil": "2024-06-01",
    "description": "Team project on designing a nozzle for efficient thrust."
  },
  {
    "_id": "A201",
    "title": "Aerodynamics Quiz",
    "course": "RS102",
    "points": 50,
    "group": "QUIZZES",
    "gradeDisplay": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-10",
    "availableFrom": "2024-05-05",
    "availableUntil": "2024-05-12",
    "description": "Quiz covering basics of aerodynamics."
  },
  {
    "_id": "A202",
    "title": "Flow Analysis",
    "course": "RS102",
    "points": 75,
    "group": "ASSIGNMENTS",
    "gradeDisplay": "Points",
    "submissionType": "On Paper",
    "onlineEntryOptions": [],
    "assignTo": "Everyone",
    "dueDate": "2024-05-18",
    "availableFrom": "2024-05-10",
    "availableUntil": "2024-05-20",
    "description": "Submit handwritten flow analysis diagrams."
  },
  {
    "_id": "A203",
    "title": "Heating Analysis",
    "course": "RS102",
    "points": 100,
    "group": "EXAMS",
    "gradeDisplay": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["File Uploads", "Text Entry"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-22",
    "availableFrom": "2024-05-15",
    "availableUntil": "2024-05-23",
    "description": "Detailed thermal analysis report."
  },
  {
    "_id": "A301",
    "title": "Structural Design Task",
    "course": "RS103",
    "points": 100,
    "group": "PROJECTS",
    "gradeDisplay": "Percentage",
    "submissionType": "Online",
    "onlineEntryOptions": ["File Uploads"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-25",
    "availableFrom": "2024-05-18",
    "availableUntil": "2024-05-27",
    "description": "Upload the CAD models and structural analysis report."
  },
  {
    "_id": "A302",
    "title": "Orbital Calculations",
    "course": "RS103",
    "points": 80,
    "group": "ASSIGNMENTS",
    "gradeDisplay": "Points",
    "submissionType": "Online",
    "onlineEntryOptions": ["Website URL", "Text Entry"],
    "assignTo": "Everyone",
    "dueDate": "2024-05-28",
    "availableFrom": "2024-05-20",
    "availableUntil": "2024-05-30",
    "description": "Submit orbital calculations and simulations link."
  },
  {
    "_id": "A303",
    "title": "Systems Engineering Exam",
    "course": "RS103",
    "points": 200,
    "group": "EXAMS",
    "gradeDisplay": "Complete/Incomplete",
    "submissionType": "On Paper",
    "onlineEntryOptions": [],
    "assignTo": "Everyone",
    "dueDate": "2024-06-01",
    "availableFrom": "2024-05-25",
    "availableUntil": "2024-06-02",
    "description": "Final exam will be held in person."
  }
]
